#!/usr/bin/perl
# File: myTest.pm

package myTest;

#use Carp;
sub printIt {
  print "myTest::printIt -> $_[0]\n";
  warn "This is a warning from myTest::printIt";
  die "die called from myTest::printIt";
  #carp "This is a carp message generated by myTest::printIt";
  #confess  "confess called from myTest::printIt";
  #croak  "croak called from myTest::printIt";
}
1;

